# -*- coding: utf-8 -*-
"""Trabajo_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRR22ZjgyRmsM-xZfzct03_V0OMRDj53

# **TRABAJO FINAL**

**Importación de librerias**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

"""**Carga dataset**"""

#Cargar el dataset
df = sns.load_dataset('car_crashes')

#Ver las primeras 5 filas del dataset
print("--- PRIMERAS FILAS DEL DATASET ---")
print(df.head())

#Ver información general (columnas, tipos de datos y nulos)
print("\n--- INFORMACIÓN GENERAL ---")
df.info()

#Ver estadísticas descriptivas básicas
print("\n--- ESTADÍSTICAS DESCRIPTIVAS ---")
print(df.describe())

# 1. Seleccionamos solo las columnas numéricas para el análisis
df_numeric = df.drop(columns=['abbrev'])

# 2. Escalamos los datos entre 0 y 1 para poder comparar variables con diferentes unidades
scaler = MinMaxScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df_numeric), columns=df_numeric.columns)

# 3. Configuración del lienzo en Colab
plt.figure(figsize=(12, 6))
sns.set_theme(style="whitegrid")

# 4. Dibujamos el Boxplot con los nombres originales en inglés
sns.boxplot(data=df_scaled, orient="h", palette="Set3", linewidth=2, fliersize=6)

plt.title('Distribución y Rango de las Variables del Dataset (Escaladas de 0 a 1)', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Escala Relativa (Mínimo a Máximo)', fontsize=12)
plt.ylabel('Variables', fontsize=12)

plt.tight_layout()
plt.show()

"""**Análisis exploratorio**"""

# Gráfico de dispersión: Alcohol vs Siniestros Totales
plt.figure(figsize=(10, 5))

sns.scatterplot(data=df, x='alcohol', y='total', hue='speeding', palette='autumn', size='total')
plt.title('Relación entre Consumo de Alcohol, Velocidad y Siniestros Mortales')
plt.xlabel('Porcentaje de Conductores Alcoholizados')
plt.ylabel('Total de Siniestros Mortales (por billón de millas)')
plt.grid(True)
plt.show()
plt.tight_layout()
# Mapa de Calor de Correlaciones
plt.figure(figsize=(9, 7))

# Calculamos la correlación omitiendo la columna de texto 'abbrev'
corr_matrix = df.drop(columns=['abbrev']).corr()

# Dibujamos el mapa de calor
sns.heatmap(corr_matrix,
            annot=True,          # Muestra los números dentro de cada celda
            cmap='coolwarm',     # Color azul para negativo, rojo para positivo
            fmt=".2f",           # Limita a 2 decimales
            linewidths=0.5,      # Añade una línea delgada de separación
            square=True)         # Hace que las celdas sean perfectamente cuadradas

plt.title('Matriz de Correlación: Factores Asociados a Siniestros Mortales', fontsize=14, pad=15)
plt.tight_layout()

# Mostramos el segundo gráfico por separado
plt.show()

#Matriz de correlación numérica
print("\n--- MATRIZ DE CORRELACIÓN ---")
# Excluimos la columna de texto 'abbrev' para calcular la correlación
print(df.drop(columns=['abbrev']).corr()['total'].sort_values(ascending=False))

"""**Prepocesamiento de datos**"""

# ============================================================
# BLOQUE 1: DIAGNÓSTICO INICIAL
# ============================================================

print("=" * 55)
print("1. FORMA DEL DATASET")
print("=" * 55)
print(f"Filas: {df.shape[0]} | Columnas: {df.shape[1]}")

print("\n" + "=" * 55)
print("2. VALORES NULOS POR COLUMNA")
print("=" * 55)
nulos = df.isnull().sum()
pct_nulos = (nulos / len(df) * 100).round(2)
reporte_nulos = pd.DataFrame({
    'Nulos': nulos,
    '% Nulos': pct_nulos
})
print(reporte_nulos)

print("\n" + "=" * 55)
print("3. REGISTROS DUPLICADOS")
print("=" * 55)
print(f"Duplicados totales: {df.duplicated().sum()}")

print("\n" + "=" * 55)
print("4. TIPOS DE DATOS")
print("=" * 55)
print(df.dtypes)

print("\n" + "=" * 55)
print("5. COLUMNAS NUMÉRICAS VS. CATEGÓRICAS")
print("=" * 55)
num_cols = df.select_dtypes(include='number').columns.tolist()
cat_cols = df.select_dtypes(include='object').columns.tolist()
print(f"Numéricas  : {num_cols}")
print(f"Categóricas: {cat_cols}")

# ============================================================
# BLOQUE 2: DETECCIÓN DE OUTLIERS MEDIANTE IQR
# ============================================================

print("=" * 55)
print("OUTLIERS POR COLUMNA (método IQR)")
print("=" * 55)

resumen_outliers = []
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lim_inf = Q1 - 1.5 * IQR
    lim_sup = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lim_inf) | (df[col] > lim_sup)]
    resumen_outliers.append({
        'Columna'  : col,
        'Lím. Inf.': round(lim_inf, 3),
        'Lím. Sup.': round(lim_sup, 3),
        'Outliers' : len(outliers),
        'Estados'  : list(outliers['abbrev']) if len(outliers) > 0 else []
    })

df_outliers = pd.DataFrame(resumen_outliers)
print(df_outliers.to_string(index=False))

# ============================================================
# BLOQUE 3: IMPUTACIÓN DE VALORES NULOS
# ============================================================

df_clean = df.copy()

# 3a. Columnas numéricas → mediana (robusta ante outliers)
for col in num_cols:
    if df_clean[col].isnull().sum() > 0:
        mediana = df_clean[col].median()
        df_clean[col].fillna(mediana, inplace=True)
        print(f"[IMPUTADO] {col} → mediana = {mediana:.4f}")
    else:
        print(f"[OK] {col} → sin nulos")

# 3b. Columnas categóricas → moda
for col in cat_cols:
    if df_clean[col].isnull().sum() > 0:
        moda = df_clean[col].mode()[0]
        df_clean[col].fillna(moda, inplace=True)
        print(f"[IMPUTADO] {col} → moda = '{moda}'")
    else:
        print(f"[OK] {col} → sin nulos")

print(f"\nNulos tras imputación: {df_clean.isnull().sum().sum()}")

# ============================================================
# BLOQUE 4: EVALUACIÓN Y DECISIÓN SOBRE FEATURES
# ============================================================

print("=" * 55)
print("ANÁLISIS DE CADA FEATURE")
print("=" * 55)

decisiones = {
    'total'          : 'CONSERVAR  — variable objetivo principal',
    'speeding'       : 'CONSERVAR  — sub-componente de total (% por exceso de velocidad)',
    'alcohol'        : 'CONSERVAR  — sub-componente de total (% por alcohol)',
    'not_distracted' : 'CONSERVAR  — complemento de distracciones; alta correlación con total',
    'no_previous'    : 'CONSERVAR  — indica reincidencia; relevante para riesgo',
    'ins_premium'    : 'CONSERVAR  — variable de respuesta económica',
    'ins_losses'     : 'CONSERVAR  — variable de respuesta económica',
    'abbrev'         : 'TRANSFORMAR → índice / excluir de modelos numéricos'
}

for feat, decision in decisiones.items():
    print(f"  {feat:<18}: {decision}")

# Establecer 'abbrev' como índice para identificación sin entrar al modelo
df_clean = df_clean.set_index('abbrev')

print("\n" + "=" * 55)
print("DATASET PREPROCESADO")
print("=" * 55)
print(df_clean.shape)
print(df_clean.head())

# ============================================================
# BLOQUE 5: VERIFICACIÓN FINAL
# ============================================================

print("=" * 55)
print("RESUMEN DEL DATASET PREPROCESADO")
print("=" * 55)
print(f"\nDimensiones      : {df_clean.shape}")
print(f"Nulos restantes  : {df_clean.isnull().sum().sum()}")
print(f"Duplicados       : {df_clean.duplicated().sum()}")
print(f"\nTipos de datos finales:")
print(df_clean.dtypes)
print(f"\nEstadísticas descriptivas:")
print(df_clean.describe().round(3))

#PARTE "2"

print("INICIANDO PIPELINE DE PREPROCESAMIENTO")

# --- 1. CARGA DEL DATASET ORIGINAL ---
df_raw = sns.load_dataset('car_crashes')

# --- 2. PREPARACIÓN DE DATOS - PARTE I (LIMPIEZA DE ENTREGABLE 1) ---
df_clean = df_raw.copy()
# abbrev se establece como índice para evitar contaminar con texto los modelos numéricos
df_clean = df_clean.set_index('abbrev')

# --- 3. FASE 3: DATA PREPARATION - PARTE II (TRANSFORMACIÓN Y ESCALADO) ---
# Separación de características (X) y variable objetivo (y)
X = df_clean.drop(columns=['total'])
y = df_clean['total']

# División del dataset en Entrenamiento (80%) y Prueba (20%) con random_state fijo para reproducibilidad
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# Escalado Estándar Z-Score (Evita que magnitudes grandes de ins_premium dominen sobre alcohol)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test) # Transformación pasiva para evitar Data Leakage

# Reconstrucción de DataFrames listos para modelar
X_train_ready = pd.DataFrame(X_train_scaled, columns=X.columns, index=X_train.index)
X_test_ready = pd.DataFrame(X_test_scaled, columns=X.columns, index=X_test.index)
print("[OK] Fase 3: Data Preparation II (División y Escalado Z-Score) completada.")

# --- 4. FASE 4: MODELADO (MODELING) - COMPARATIVA MULTIMODELO ---
# Configuración y control de hiperparámetros para mitigar sobreajuste
modelos = {
    "Regresión Lineal Múltiple": LinearRegression(),
    "Árbol de Decisión": DecisionTreeRegressor(random_state=42, max_depth=4),
    "Random Forest": RandomForestRegressor(random_state=42, n_estimators=100, max_depth=4),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42, n_estimators=100, learning_rate=0.1, max_depth=3)
}

# Entrenamiento masivo en bucle competitivo bajo el mismo escenario experimental
modelos_entrenados = {}
for nombre, algoritmo in modelos.items():
    algoritmo.fit(X_train_ready, y_train)
    modelos_entrenados[nombre] = algoritmo
print("[OK] Fase 4: Modeling (Entrenamiento competitivo de 4 algoritmos) completado.")

# --- 5. FASE 5: EVALUACIÓN (EVALUATION) Y ELECCIÓN DEL GANADOR ---
tabla_resultados = []
for nombre, modelo in modelos_entrenados.items():
    # Predicciones sobre ambos conjuntos para evaluar Overfitting
    y_pred_train = modelo.predict(X_train_ready)
    y_pred_test = modelo.predict(X_test_ready)

    # Cálculo formal de métricas
    mae = mean_absolute_error(y_test, y_pred_test)
    mse = mean_squared_error(y_test, y_pred_test)
    rmse = np.sqrt(mse)
    r2_test = r2_score(y_test, y_pred_test)
    r2_train = r2_score(y_train, y_pred_train)

    tabla_resultados.append({
        "Modelo": nombre,
        "MAE (Test)": round(mae, 4),
        "RMSE (Test)": round(rmse, 4),
        "R² (Test)": round(r2_test, 4),
        "R² (Train)": round(r2_train, 4),
        "Overfitting (Δ R²)": round(r2_train - r2_test, 4)
    })

df_resultados = pd.DataFrame(tabla_resultados).sort_values(by="RMSE (Test)")
print("\n--- TABLA COMPARATIVA DE RENDIMIENTO (ORDENADA POR RMSE) ---")
print(df_resultados.to_string(index=False))

# Generación de visualizaciones comparativas de métricas de error y varianza
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
sns.set_theme(style="whitegrid")
sns.barplot(data=df_resultados, x="RMSE (Test)", y="Modelo", palette="Reds_r", ax=axes[0])
axes[0].set_title("Raíz del Error Cuadrático Medio (RMSE) - ¡Menor es Mejor!")
sns.barplot(data=df_resultados, x="R² (Test)", y="Modelo", palette="Blues_r", ax=axes[1])
axes[1].set_title("Coeficiente de Determinación (R²) - ¡Mayor es Mejor!")
plt.tight_layout()
plt.show()

# Extracción de la importancia de variables del modelo ganador (Decisión Final: Random Forest)
ganador_name = "Random Forest"
modelo_ganador = modelos_entrenados[ganador_name]
importancias = modelo_ganador.feature_importances_ # Corrected: changed __ to _
indices_ordenados = np.argsort(importancias)[::-1]

plt.figure(figsize=(10, 5))
sns.barplot(x=importancias[indices_ordenados], y=X.columns[indices_ordenados], palette="viridis")
plt.title(f"Decisión Final - Importancia de Características según: {ganador_name}", fontsize=12, fontweight='bold')
plt.xlabel("Peso Relativo en las Predicciones (Ganancia de Información)")
plt.ylabel("Variables del Dataset")
plt.show()
print("[OK] Fase 5: Evaluation (Cálculo de métricas, gráficos e importancia de variables) completada.")

# --- 6. FASE 6: DESPLIEGUE (DEPLOYMENT) ---
# Exportación y congelamiento de binarios para puesta en producción
with open('scaler_car_crashes.pkl', 'wb') as f_scaler:
    pickle.dump(scaler, f_scaler)

with open('model_car_crashes.pkl', 'wb') as f_model:
    pickle.dump(modelo_ganador, f_model)

print("\n[OK] Fase 6: Deployment (Exportación de scaler_car_crashes.pkl y model_car_crashes.pkl) exitosa.")
print("=== PIPELINE FINALIZADO CORRECTAMENTE. LISTO PARA ENTREGA ===")